"""Build theme-dark.css: every rule the light theme recoloured, restored to its
benchmark (dark) version and scoped to :root[data-theme="dark"].

usage:
  git show benchmark-2026-10-09:src/app/globals.css > /tmp/old.css
  python3 scripts/gen-dark-theme.py /tmp/old.css src/app/globals.css src/app/theme-dark.css
"""
import sys

old_path, new_path, out_path = sys.argv[1:4]
old = open(old_path).read()
new = open(new_path).read()
old_lines, new_lines = old.split("\n"), new.split("\n")
assert len(old_lines) == len(new_lines), "line counts differ"
changed = {i for i, (a, b) in enumerate(zip(old_lines, new_lines)) if a != b}

# Parse blocks of the OLD file: (header, body_start, end, parents, start_line, end_line)
blocks, stack = [], []
line, last, i, quote = 0, 0, 0, None
in_comment = False
while i < len(old):
    c = old[i]
    if in_comment:
        if old.startswith("*/", i):
            in_comment = False
            i += 1
    elif quote:
        if c == quote:
            quote = None
    elif old.startswith("/*", i):
        in_comment = True
    elif c in "\"'":
        quote = c
    elif c == "{":
        header = old[last:i].strip()
        # drop any trailing declarations / comments before the header
        header = header.split(";")[-1].split("*/")[-1].strip()
        stack.append((header, i + 1, line))
        last = i + 1
    elif c == "}":
        header, body_start, start_line = stack.pop()
        blocks.append((header, body_start, i, [h for h, _, _ in stack], start_line, line))
        last = i + 1
    elif c == ";":
        last = i + 1
    if c == "\n":
        line += 1
    i += 1

def innermost(ln):
    best = None
    for b in blocks:
        if b[0].startswith("@") or b[0] in ("from", "to") or b[0].endswith("%"):
            continue
        if b[4] <= ln <= b[5] and (best is None or (b[5] - b[4]) < (best[5] - best[4])):
            best = b
    return best

def scope(sel):
    sel = sel.strip()
    if sel.startswith(":root"):
        return ':root[data-theme="dark"]' + sel[5:]
    if sel.startswith("html"):
        return 'html[data-theme="dark"]' + sel[4:]
    return ':root[data-theme="dark"] ' + sel

seen, out = set(), []
for ln in sorted(changed):
    b = innermost(ln)
    if b is None:
        print("unmatched line", ln + 1, old_lines[ln].strip(), file=sys.stderr)
        continue
    key = (b[1], b[2])
    if key in seen:
        continue
    seen.add(key)
    if any(p.startswith("@keyframes") for p in b[3]):
        continue
    selectors = ",\n".join(scope(s) for s in b[0].split(","))
    # keep only the declarations that touch a changed line
    decls, depth, startc = [], 0, b[1]
    for j in range(b[1], b[2] + 1):
        ch = old[j] if j < b[2] else ";"
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == ";" and depth == 0:
            text = old[startc:j]
            l0 = old.count("\n", 0, startc) + (len(text) - len(text.lstrip("\n ")) and text[: len(text) - len(text.lstrip())].count("\n"))
            l1 = old.count("\n", 0, j)
            if text.strip() and any(l0 <= k <= l1 for k in changed):
                decls.append("  " + " ".join(x.strip() for x in text.strip().split("\n")) + ";")
            startc = j + 1
    if not decls:
        continue
    body = "\n".join(decls)
    rule = f"{selectors} {{\n{body}\n}}"
    for p in reversed([p for p in b[3] if p.startswith("@")]):
        rule = f"{p} {{\n{rule}\n}}"
    out.append(rule)

header = (
    "/* GENERATED by scripts/gen-dark-theme.py from the benchmark (tag benchmark-2026-10-09).\n"
    "   Dark mode = the benchmark look: every rule the light theme recoloured,\n"
    "   restored and scoped to :root[data-theme=\"dark\"]. */\n\n"
)
open(out_path, "w").write(header + "\n\n".join(out) + "\n")
print(len(changed), "changed lines ->", len(out), "rules")
